### PR TITLE
Use fully qualified path to Diff trait.

### PR DESCRIPTION
**Pull request by vriesk**
Rationale:
This allows the macro to work when the `Diff` trait is not in the current scope, e.g. when used from another macro or from `#[derive(::diff::Diff)]`.

### CODE REVIEW

**Comment by benhall-7** [comment]
Hey! Sorry for the delay, I saw this but it was right before Thanksgiving so I got busy. I'll test it soon

**Comment by benhall-7** [comment]
So I think this works in most contexts, but it does bring up some issues. Namely, diff-struct itself can't use the derive macro because Diff is located in `crate::Diff` instead of `diff::Diff`. I think for maximum scalability, it'd be best to have a derive attribute that lets the user specify the path, and so that would default to `::diff`. I'll try to implement that and post the diff here

**Comment by benhall-7** [comment]
Ok, I've implemented the thing I mentioned and everything seems to work as expected. Instead of posting here, I figured I will just merge and push a new commit with the adjustments, then I'll reply here again once I've released the new version

**Comment by benhall-7** [comment]
Please let me know if it's not working for you, but I'm pretty confident that it's good to go! diff-struct is on version 0.5.1 now

**Comment by vriesk** [comment]
Thanks! This works well for me :)

**Pull request merged**
