### PR TITLE
Add support for type parameters.

### PR DESCRIPTION
**Pull request by azriel91**
Heya, I added support for types with type parameters.

I've also got tests for them in `diff-struct`, shall push that soon.

### CODE REVIEW

**Comment by benhall-7** [comment]
Hey, thanks! I'll review tonight

**Comment by azriel91** [comment]
oh yes, there's a bug with tuples with generics, I'll push a fix tonight

**Comment by azriel91** [comment]
pushed :+1: (here and on https://github.com/BenHall-7/diff-struct/pull/8)

**Review by benhall-7 — CHANGES_REQUESTED** [review]
So I'm playing around with this and there are two main things I think we should account for:

1. Type constraints can be written in this form too: `<A: PartialEq>`, or a mixture of both (not that people would do that), and this currently causes an exception.
2. A derived struct's type parameters don't necessarily have to implement PartialEq, and it's not clear to me why we should make that assumption. I think the minimum possible constraint, just adding Diff, is the best option. For example, this is how Debug is derived on such a type:

```rust
struct UnnamedGenerics<A: Diff, B>(A, B);

impl<A: Debug + Diff, B: Debug> Debug for UnnamedGenerics<A, B> {
```

In their case, they put the Debug constraint in the brackets, but the 'where' clause is equally valid, so that much doesn't matter to me.

If we needed to modify the constraints of the derived type, I think that would be a good opportunity to use a struct-level attribute. If it isn't super important, I think that would be best as a followup PR. What do you think?

**Comment by azriel91** [comment]
ah good catch -- I normally write trait bounds separately out of habit. I'll probably work on it this weekend

**Comment by azriel91** [comment]
heya, got that part to work and added tests as well :v:

**Review by benhall-7 — APPROVED** [review]
Thanks a lot!

**Pull request merged**
